FORMAT: 1A
HOST: https://qualpro.herokuapp.com

# qualPro API

## General Errors

Http Code | Error Type           |  Error                             | Details
---------:| -------------------- |  --------------------------------- | ----------------
403       | AuthError            |  Not Authorized                    |
404       | Not Found            |  Page Not Found                    |
400       | Bad request          |  Not enough incoming parameters    |
400       | Bad request          |  ValidationError                   | Reasons of error
500       | Internal error       |  Internal server error             |

# Data Structures

## GenericError
+ error:`Some error description.` (string)

## CreateContactUs
+ type (enum, required)
    + Members
        + Application Related Issue
        + Future Application Ideas
        + Others
+ description: `some description` (string, required)
+ file: `1Virtyv.jpg` (optional) - file in multipart/form-data

## UpdateContactUs
+ comment: `some comment` (string)
+ status (enum)
    + Members
        + resolved

## CreateContactUsRes
+ _id: `5818b01a13187de020871b63` (string)
+ createdBy: `5818b01a13187de020871b63` (string)
+ attachments: `5818b01a13187de020871b63` (string)
+ type: `Others` (string)
+ description: `test bug` (string)
+ status: `new` (string)
+ createdAt: `2016-11-01T13:09:14.000Z` (string)

## Country
+ _id: `5818b01a13187de020871b63` (string)
+ name
    + ar (string)
    + en: USA (string)

## Category
+ _id: `5818b01a13187de020871b63` (string)
+ name
    + ar (string)
    + en: TUNA (string)

## Branch
+ _id: `5818b01a13187de020871b63` (string)
+ name
    + ar (string)
    + en: `ABA MONOPRIX QATAR` (string)

## DisplayType
+ _id: 16 (number)
+ name
    + ar (string)
    + en: `Promoter Stand` (string)

## Outlet
+ _id: 16 (number)
+ name
    + ar (string)
    + en: CARREFOUR (string)

## File
+ _id: `5818b01a13187de020871b63` (string)
+ name: `57dbf068843d1c6e3a162bd9.jpg`(string)
+ originalName: `pupok.jpg` (string)
+ url: `https://s3.amazonaws.com/` (string)

## ContactUsById
+ _id: `5818b01a13187de020871b63` (string)
+ type: `Others` (string)
+ description: `test bug` (string)
+ status: `new` (string)
+ createdAt: `2016-11-01T13:09:14.000Z` (string)
+ creator
    + _id: `5818b01a13187de020871b63` (string)
    + ID: 153 (number)
    + country (array[Country])
    + lastName
        + en (string)
        + ar (string)
    + firstName
        + en (string)
        + ar (string)
+ file
    + originalName (string)
    + name (string)
    + url (string)

## ContactUsShort
+ _id: `5818b01a13187de020871b63` (string)
+ type: `Others` (string)
+ description: `test bug` (string)
+ status: `new` (string)
+ createdAt: `2016-11-01T13:09:14.000Z` (string)
+ creator
    + _id: `5818b01a13187de020871b63` (string)
    + ID: 153 (number)
    + lastName
        + en (string)
        + ar (string)
    + firstName
        + en (string)
        + ar (string)

## BrandingAndDisplayCreate
+ branch: `5818b01a13187de020871b63` (string, required)
+ outlet: `5818b01a13187de020871b63` (string, required)
+ categories: `5818b01a13187de020871b63` (array)
+ description: something (string, required)
+ displayType: 10 (number)
    + Default: 16
+ dateStart: `2016-11-01T13:09:14.000Z` (string)
+ dateEnd: `2016-11-01T13:09:14.000Z` (string)

## BrandingAndDisplayCreateRes
+ _id: `5818b01a13187de020871b63` (string)
+ createdBy: `5818b01a13187de020871b63` (string)
+ outlet: `5818b01a13187de020871b63` (string)
+ branch: `5818b01a13187de020871b63` (string)
+ attachments: `5818b01a13187de020871b63` (array)
+ description: hhfhf (string)
+ dateStart: `2016-11-01T13:09:14.000Z` (string)
+ dateEnd: `2016-11-01T13:09:14.000Z` (string)
+ createdAt: `2016-11-01T13:09:14.000Z` (string)

## BrandingAndDisplayById
+ _id: `5818b01a13187de020871b63` (string)
+ attachments (array[File])
+ categories (array[Category])
+ branch (Branch)
+ outlet (Outlet)
+ displayType (DisplayType)
+ description: hhfhf (string)
+ dateStart: `2016-11-01T13:09:14.000Z` (string)
+ dateEnd: `2016-11-01T13:09:14.000Z` (string)
+ createdAt: `2016-11-01T13:09:14.000Z` (string)
+ createdBy
    + _id: `5818b01a13187de020871b63` (string)
    + ID: 153 (number)
    + lastName
        + en (string)
        + ar (string)
    + firstName
        + en (string)
        + ar (string)
    + country (array[Country])
    + region (array[Country])
    + subRegion (array[Country])

## BrandingAndDisplayShort
+ _id: `5818b01a13187de020871b63` (string)
+ categories (array[Category])
+ branch (Branch)
+ outlet (Outlet)
+ displayType (DisplayType)
+ description: hhfhf (string)
+ dateStart: `2016-11-01T13:09:14.000Z` (string)
+ dateEnd: `2016-11-01T13:09:14.000Z` (string)
+ createdAt: `2016-11-01T13:09:14.000Z` (string)
+ createdBy
    + _id: `5818b01a13187de020871b63` (string)
    + ID: 153 (number)
    + lastName
        + en (string)
        + ar (string)
    + firstName
        + en (string)
        + ar (string)

# Group ContactUs

## Send contactUs form [/mobile/contactUs]

### Create [POST]
Create contact us form.

+ Request (multipart/form-data)
    + Attributes (CreateContactUs)
+ Response 200 (application/json)
    + Attributes (CreateContactUsRes)
+ Response 400 (application/json)
    + Attributes (GenericError)

## Get all contactUs form [/contactUs{?page,count,sortBy,filter}]

### Get all [GET]
Get contact us forms.

+ Parameters
    + page: 3 (number)
        + Default: 1
    + count: 50 (number)
        + Default: 25
    + sortBy: `-createdAt` (string) - parameter for sorting, default order ASC add prefix `-` for DESC
    + filter (object, optional)
        + type (object, optional)
            + values (array)
            + Members
                + `Application Related Issue`
                + `Future Application Ideas`
                + `Others`

        + status (object)
            + values (array)
            + Members
                + `new`
                + `resolved`
        + personnel (object)
            + values (array)
        + position (object)
            + values (array)
        + startDate: `2016-11-06 13:41:46` (string)
            + Default: `start of the year`
        + endDate: `2016-11-06 13:41:46` (string)
            + Default: `current date`

+ Request (application/json)
+ Response 200 (application/json)
    + Attributes
        + total: 1 (number)
        + data (array[ContactUsShort])
+ Response 400 (application/json)
    + Attributes (GenericError)

## Get By Id contactUs form [/contactUs/{id}]

### Get By Id [GET]
Get contact us form by id.

+ Parameters
    + id - form _id

+ Request (application/json)
+ Response 200 (application/json)
    + Attributes (ContactUsById)
+ Response 400 (application/json)
    + Attributes (GenericError)

## Update By Id contactUs form [/contactUs/{id}]

### Update By Id [PUT]
Get contact us form by id.

+ Parameters
    + id - form _id

+ Request (application/json)
    + Attributes (UpdateContactUs)
+ Response 200 (application/json)
    + Attributes (CreateContactUsRes)
+ Response 400 (application/json)
    + Attributes (GenericError)

# Group BrandingAndDisplayReport

## Create brandingAndDisplay [/mobile/brandingAndDisplay]

### Create [POST]
Create brandingAndDisplay report.

+ Request (multipart/form-data)
    + Attributes (BrandingAndDisplayCreate)
+ Response 200 (application/json)
    + Attributes (BrandingAndDisplayCreateRes)
+ Response 400 (application/json)
    + Attributes (GenericError)

## Create brandingAndDisplay By Id [/mobile/brandingAndDisplay]

### Get By Id [GET]
Get brandingAndDisplay report by id.

+ Parameters
    + id

+ Request (application/json)
+ Response 200 (application/json)
    + Attributes (BrandingAndDisplayById)
+ Response 400 (application/json)
    + Attributes (GenericError)

## Get all brandingAndDisplay reports [/brandingAndDisplay{?page,count,sortBy,filter}]

### Get all [GET]
Get brandingAndDisplay reports.

+ Parameters
    + page: 3 (number)
        + Default: 1
    + count: 50 (number)
        + Default: 25
    + sortBy: `-createdAt` (string) - parameter for sorting, default order ASC add prefix `-` for DESC
    + filter (object, optional)
        + startDate: `2016-11-06 13:41:46` (string)
            + Default: `start of the year`
        + endDate: `2016-11-06 13:41:46` (string)
            + Default: `current date`
        + categories (object, optional)
            + values: `5818b01a13187de020871b63`, `5818b01a13187de020871b63` (array)
        + createdBy (object, optional)
            + values: [5818b01a13187de020871b63] (array)
        + outlet (object, optional)
            + values: [5818b01a13187de020871b63] (array)
        + branch (object, optional)
            + values: [5818b01a13187de020871b63] (array)
        + country (object, optional)
            + values: [5818b01a13187de020871b63] (array)
        + region (object, optional)
            + values: [5818b01a13187de020871b63] (array)
        + subRegion (object, optional)
            + values: [5818b01a13187de020871b63] (array)
        + position (object, optional)
            + values: [5818b01a13187de020871b63] (array)


+ Request (application/json)
+ Response 200 (application/json)
    + Attributes
        + total: 1 (number)
        + data (array[BrandingAndDisplayShort])
+ Response 400 (application/json)
    + Attributes (GenericError)