module.exports = {
    SUPER_ADMIN: 0,
    MASTER_ADMIN: 1,
    COUNTRY_ADMIN: 2,
    AREA_MANAGER: 3,
    AREA_IN_CHARGE: 4,
    SALES_MAN: 5,
    MERCHANDISER: 6,
    CASH_VAN: 7,
    MASTER_UPLOADER: 8,
    COUNTRY_UPLOADER: 9,
    TRADE_MARKETER: 10,
    VIRTUAL: 11,
    PROMOTER: 12
};
