const aclModules = require('./../../constants/aclModulesNames');

module.exports = {
    ADD_ACTIVITY_LIST: `ADD_${aclModules.ACTIVITY_LIST}`,
    CLEANUP_ACTIVITY_LIST: `CLEANUP_${aclModules.ACTIVITY_LIST}`,

    ADD_COUNTRY: `ADD_${aclModules.COUNTRY}`,
    ADD_REGION: `ADD_${aclModules.REGION}`,
    ADD_SUB_REGION: `ADD_${aclModules.SUB_REGION}`,
    CLEANUP_COUNTRIES: `CLEANUP_${aclModules.COUNTRY}`,

    ADD_CUSTOMER: `ADD_${aclModules.CUSTOMER}`,
    ADD_BRANCH: `ADD_${aclModules.BRANCH}`,
    CLEANUP_CUSTOMER: `CLEANUP_${aclModules.CUSTOMER}`,

    ADD_TRADE_CHANNEL: `ADD_${aclModules.TRADE_CHANNEL}`,
    CLEANUP_TRADE_CHANNEL: `CLEANUP_${aclModules.CUSTOMER}`,

    ADD_PERSONNEL: `ADD_${aclModules.PERSONNEL}`,
    ADD_OBJECTIVE: `ADD_${aclModules.OBJECTIVE}`,
    ADD_IN_STORE_REPORTING: `ADD_${aclModules.IN_STORE_REPORTING}`,
    ADD_ITEMS_AND_PRICES: `ADD_${aclModules.ITEMS_AND_PRICES}`,
    ADD_PLANOGRAM: `ADD_${aclModules.PLANOGRAM}`,
    ADD_COMPETITOR_LIST: `ADD_${aclModules.COMPETITOR_LIST}`,

    ADD_COMPETITOR_PROMOTION_ACTIVITIES: `ADD_${aclModules.COMPETITOR_PROMOTION_ACTIVITY}`,
    ADD_PROMO_EVALUATION: `ADD_${aclModules.AL_ALALI_PROMO_EVALUATION}`,
    ADD_PROMOTION_ITEMS: `ADD_${aclModules.AL_ALALI_PROMOTIONS_ITEMS}`,
    ADD_COMPETITOR_BRANDING_DISPLAY_REPORT: `ADD_${aclModules.COMPETITOR_BRANDING_DISPLAY_REPORT}`,
    ADD_ACHIEVEMENT_FORM: `ADD_${aclModules.ACHIEVEMENT_FORM}`,
    ADD_NEW_PRODUCT_LAUNCH: `ADD_${aclModules.NEW_PRODUCT_LAUNCH}`,
    ADD_SHELF_SHARES: `ADD_${aclModules.SHELF_SHARES}`,
    ADD_PRICE_SURVEY: `ADD_${aclModules.PRICE_SURVEY}`,

    ADD_QUESTIONNAIRE: `ADD_${aclModules.AL_ALALI_QUESTIONNAIRE}`,
    ADD_MARKETING_CAMPAIGNS: `ADD_${aclModules.AL_ALALI_BRANDING_ACTIVITY}`,
    ADD_CONSUMER_SURVEY: `ADD_${aclModules.CONSUMER_SURVEY}`,
    ADD_BRANDING_AND_MONTHLY_DISPLAY: `ADD_${aclModules.AL_ALALI_BRANDING_DISPLAY_REPORT}`,

    ADD_CONTRACT_YEARLY_AND_VISIBILITY: `ADD_${aclModules.CONTRACT_YEARLY_AND_VISIBILITY}`,
    ADD_CONTRACT_SECONDARY: `ADD_${aclModules.CONTRACT_SECONDARY}`,

    ADD_NOTE: `ADD_${aclModules.NOTE}`,
    ADD_NOTIFICATION: `ADD_${aclModules.NOTIFICATION}`,
    ADD_DOCUMENT: `ADD_${aclModules.DOCUMENT}`,
    ADD_CONTACT_US: `ADD_${aclModules.CONTACT_US}`,
};
