module.exports = {
    _id: 1,
    title: 1,
    description: 1,
    objectiveType: 1,
    priority: 1,
    status: 1,
    assignedTo: 1,
    complete: 1,
    level: 1,
    dateStart: 1,
    dateEnd: 1,
    dateClosed: 1,
    comments: 1,
    attachments: 1,
    editedBy: 1,
    createdBy: 1,
    country: 1,
    region: 1,
    subRegion: 1,
    retailSegment: 1,
    outlet: 1,
    branch: 1,
    location: 1,
    form: 1,
    history: 1,
    creationDate: 1,
    updateDate   : 1
};
